### ISSUE TITLE
error 3

### ISSUE THREAD

**Issue by xxcriticxx** [Jo2003/vlc_record#10]
iptv1world.com error:
Host core.iptv1world.com not found (`#3`)

can you please tell me more about this error and how to prevent it

**Comment by Jo2003** [comment]
The server of your provider isn't reachable.                                                                                                                                                                         Gesendet über BlackBerry Hub für Android                                                                                                                                                                           Von: notifications@github.comGesendet: 26. November 2017 1:10 vorm.An: vlc_record@noreply.github.comAntworten: reply@reply.github.comCc: subscribed@noreply.github.comBetreff: [Jo2003/vlc_record] error 3 (#10)  iptv1world.com error:
Host core.iptv1world.com not found (#3)
can you please tell me more about this error and how to prevent it

**Comment by xxcriticxx** [comment]
why do i lose mouse? i cant click on it with mouse

**Comment by Jo2003** [comment]
Sorry, when do you lose mouse? If I should help you, give some more detailed information.Jörg                                                                                                                                                                        Gesendet über BlackBerry Hub für Android                                                                                                                                                                           Von: notifications@github.comGesendet: 26. November 2017 2:21 vorm.An: vlc_record@noreply.github.comAntworten: reply@reply.github.comCc: olenka.joerg@gmail.com; comment@noreply.github.comBetreff: Re: [Jo2003/vlc_record] error 3 (#10)  why do i lose mouse? i cant click on it with mouse

**Comment by xxcriticxx** [comment]
once the msg pop up mouse arrow disappears only way to click ok is to use enter on the keyboard

**Comment by xxcriticxx** [comment]
@Jo2003 anything i can do to get mouse to work again?

**Comment by Jo2003** [comment]
Should I buy you a new one? 
When mouse pointer disappears? Which popup window? What to do to reproduce this behavior?

**Comment by xxcriticxx** [comment]
![img_1459](https://user-images.githubusercontent.com/15007183/33343564-c2266c4e-d453-11e7-84c9-79e5ce1c4ecd.JPG)

this msg comes out and pointer disappears only have to get up to the keyboard to hit enter to close the msg

**Comment by Jo2003** [comment]
You are watching video in fullscreen. Therefore mouse pointer disappears. Mouse pointer would be shown again, when the video widget gets mouse move events. Now the popup gets focus. Means the video widget which is responsible for mouse hiding / showing doesn't get any mouse move event anymore because they are sent to the widget with focus (popup). Therefore the mouse pointer is still hidden. Normally you simple would make a mouse click on the video (even if mouse isn't shown) and the video widget would get focus and mouse events would make the pointer visible. But I think this doesn't work because the message popup stays in focus. 

This is something I will not investigate in. The whole mouse hide / show stuff is no simple task and chances are good I would break another task while "fixing" this little issue. Talk with your provider and ask why you get this error message!

**Comment by xxcriticxx** [comment]
ok roger
